"""
This family file was auto-generated by generate_family_file.py script.

Configuration parameters:
  url = https://wiki.ontracknorthamerica.org/api.php
  name = ontrackwiki

Please do not commit this to the Git repository!
"""
from pywikibot import family


class Family(family.Family):  # noqa: D101

    name = 'ontrackwiki'
    langs = {
        'en': 'wiki.ontracknorthamerica.org',
        
    }

    def scriptpath(self, code):
        return {
            'en': '',
        }[code]

    def protocol(self, code):
        return {
            'en': 'https',
        }[code]